// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module ClockSinkDomain_1(	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [11:0] auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [14:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [11:0] auto_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_clock_in_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_clock_in_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        io_sram_on,	// @[generators/chipyard/src/main/scala/example/GCD.scala:526:16]
  input         io_sram_rdy,	// @[generators/chipyard/src/main/scala/example/GCD.scala:526:16]
  output [7:0]  io_sram_data	// @[generators/chipyard/src/main/scala/example/GCD.scala:526:16]
);

  wire              _out_wofireMux_T_2;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire              out_backSel_4;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [31:0]       _impl_io_impl_key_0;	// @[generators/chipyard/src/main/scala/example/GCD.scala:540:26]
  wire [31:0]       _impl_io_impl_key_1;	// @[generators/chipyard/src/main/scala/example/GCD.scala:540:26]
  wire [31:0]       _impl_io_impl_key_2;	// @[generators/chipyard/src/main/scala/example/GCD.scala:540:26]
  wire [31:0]       _impl_io_impl_key_3;	// @[generators/chipyard/src/main/scala/example/GCD.scala:540:26]
  wire [31:0]       _impl_io_impl_unstability;	// @[generators/chipyard/src/main/scala/example/GCD.scala:540:26]
  wire              _impl_io_impl_busy;	// @[generators/chipyard/src/main/scala/example/GCD.scala:540:26]
  wire              _impl_io_impl_valid;	// @[generators/chipyard/src/main/scala/example/GCD.scala:540:26]
  reg  [31:0]       key_size;	// @[generators/chipyard/src/main/scala/example/GCD.scala:529:25]
  reg  [31:0]       cycles;	// @[generators/chipyard/src/main/scala/example/GCD.scala:530:23]
  reg  [31:0]       start_address;	// @[generators/chipyard/src/main/scala/example/GCD.scala:531:30]
  wire              in_bits_read = auto_in_a_bits_opcode == 3'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36]
  wire              _out_T_19 = auto_in_a_bits_address[11:6] == 6'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:75:19, :87:24]
  wire [31:0]       out_backMask = {{8{auto_in_a_bits_mask[3]}}, {8{auto_in_a_bits_mask[2]}}, {8{auto_in_a_bits_mask[1]}}, {8{auto_in_a_bits_mask[0]}}};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign out_backSel_4 = auto_in_a_bits_address[5:2] == 4'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [15:0]       _GEN = {{1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {|{_impl_io_impl_valid | out_backMask == 32'h0, auto_in_a_bits_address[11:6]}}, {|{_impl_io_impl_valid | out_backMask == 32'h0, auto_in_a_bits_address[11:6]}}, {|{_impl_io_impl_valid | out_backMask == 32'h0, auto_in_a_bits_address[11:6]}}, {|{_impl_io_impl_valid | out_backMask == 32'h0, auto_in_a_bits_address[11:6]}}, {|{_impl_io_impl_valid | out_backMask == 32'h0, auto_in_a_bits_address[11:6]}}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}};	// @[generators/chipyard/src/main/scala/example/GCD.scala:540:26, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:75:19, :87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  assign _out_wofireMux_T_2 = auto_in_a_valid & auto_in_d_ready & ~in_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36, :87:24]
  wire              out_oready = ~in_bits_read | _GEN[auto_in_a_bits_address[5:2]];	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36, :87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  wire              out_front_ready = auto_in_d_ready & out_oready;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire              out_valid = auto_in_a_valid & out_oready;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [15:0]       _GEN_0 = {{1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {1'h1}, {_out_T_19}, {_out_T_19}, {_out_T_19}, {_out_T_19}, {_out_T_19}, {_out_T_19}, {_out_T_19}, {_out_T_19}, {_out_T_19}, {_out_T_19}};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
  wire [15:0][31:0] _GEN_1 = {{32'h0}, {32'h0}, {32'h0}, {32'h0}, {32'h0}, {32'h0}, {_impl_io_impl_unstability}, {_impl_io_impl_key_3}, {_impl_io_impl_key_2}, {_impl_io_impl_key_1}, {_impl_io_impl_key_0}, {32'h0}, {32'h0}, {32'h0}, {32'h0}, {{29'h0, io_sram_rdy, _impl_io_impl_valid, _impl_io_impl_busy}}};	// @[generators/chipyard/src/main/scala/example/GCD.scala:540:26, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:{10,48}]
  wire [2:0]        nodeIn_d_bits_opcode = {2'h0, in_bits_read};	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36, :105:19]
  always @(posedge auto_clock_in_clock) begin	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
    if (_out_wofireMux_T_2 & auto_in_a_bits_address[5:2] == 4'h1 & _out_T_19 & (&out_backMask))	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      key_size <= auto_in_a_bits_data;	// @[generators/chipyard/src/main/scala/example/GCD.scala:529:25]
    if (_out_wofireMux_T_2 & auto_in_a_bits_address[5:2] == 4'h2 & _out_T_19 & (&out_backMask))	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      cycles <= auto_in_a_bits_data;	// @[generators/chipyard/src/main/scala/example/GCD.scala:530:23]
    if (_out_wofireMux_T_2 & auto_in_a_bits_address[5:2] == 4'h3 & _out_T_19 & (&out_backMask))	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
      start_address <= auto_in_a_bits_data;	// @[generators/chipyard/src/main/scala/example/GCD.scala:531:30]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
      `FIRRTL_BEFORE_INITIAL	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:2];	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
    initial begin	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
        `INIT_RANDOM_PROLOG_	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
        end	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
        key_size = _RANDOM[2'h0];	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9, :529:25]
        cycles = _RANDOM[2'h1];	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9, :530:23]
        start_address = _RANDOM[2'h2];	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9, :531:30]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
      `FIRRTL_AFTER_INITIAL	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLMonitor_50 monitor (	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
    .clock                (auto_clock_in_clock),
    .reset                (auto_clock_in_reset),
    .io_in_a_ready        (out_front_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .io_in_a_valid        (auto_in_a_valid),
    .io_in_a_bits_opcode  (auto_in_a_bits_opcode),
    .io_in_a_bits_param   (auto_in_a_bits_param),
    .io_in_a_bits_size    (auto_in_a_bits_size),
    .io_in_a_bits_source  (auto_in_a_bits_source),
    .io_in_a_bits_address (auto_in_a_bits_address),
    .io_in_a_bits_mask    (auto_in_a_bits_mask),
    .io_in_a_bits_corrupt (auto_in_a_bits_corrupt),
    .io_in_d_ready        (auto_in_d_ready),
    .io_in_d_valid        (out_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .io_in_d_bits_opcode  (nodeIn_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:105:19]
    .io_in_d_bits_size    (auto_in_a_bits_size),
    .io_in_d_bits_source  (auto_in_a_bits_source)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Nodes.scala:27:25]
  SecurityPeripheral #(
    .MAX_CYCLES(127),
    .METRIC_SIZE(4),
    .WORDS(4)
  ) impl_io_impl (	// @[generators/chipyard/src/main/scala/example/GCD.scala:540:26]
    .clock         (auto_clock_in_clock),
    .reset         (auto_clock_in_reset),
    .key_size      (key_size),	// @[generators/chipyard/src/main/scala/example/GCD.scala:529:25]
    .cycles        (cycles),	// @[generators/chipyard/src/main/scala/example/GCD.scala:530:23]
    .start_address (start_address),	// @[generators/chipyard/src/main/scala/example/GCD.scala:531:30]
    .start         (_out_wofireMux_T_2 & out_backSel_4 & _out_T_19 & auto_in_a_bits_mask[0]),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .key_0         (_impl_io_impl_key_0),
    .key_1         (_impl_io_impl_key_1),
    .key_2         (_impl_io_impl_key_2),
    .key_3         (_impl_io_impl_key_3),
    .unstability   (_impl_io_impl_unstability),
    .sram_on       (io_sram_on),
    .sram_rdy      (io_sram_rdy),
    .read_data     (io_sram_data),
    .busy          (_impl_io_impl_busy),
    .valid         (_impl_io_impl_valid)
  );	// @[generators/chipyard/src/main/scala/example/GCD.scala:540:26]
  assign auto_in_a_ready = out_front_ready;	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_in_d_valid = out_valid;	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_in_d_bits_opcode = nodeIn_d_bits_opcode;	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:105:19]
  assign auto_in_d_bits_size = auto_in_a_bits_size;	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
  assign auto_in_d_bits_source = auto_in_a_bits_source;	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9]
  assign auto_in_d_bits_data = _GEN_0[auto_in_a_bits_address[5:2]] ? _GEN_1[auto_in_a_bits_address[5:2]] : 32'h0;	// @[generators/chipyard/src/main/scala/example/GCD.scala:525:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, generators/rocket-chip/src/main/scala/util/MuxLiteral.scala:49:10]
endmodule

