// Generated by CIRCT firtool-1.75.0
module DCacheDataArray(	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7]
  input         clock,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:49:7]
  input         io_req_valid,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input  [9:0]  io_req_bits_addr,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input         io_req_bits_write,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input  [31:0] io_req_bits_wdata,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  input  [3:0]  io_req_bits_eccMask,	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
  output [31:0] io_resp_0	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:50:14]
);

  wire rockettile_dcache_data_arrays_0_rdata_data_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:77:39]
  wire rockettile_dcache_data_arrays_0_rdata_MPORT_en;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17]
  assign rockettile_dcache_data_arrays_0_rdata_MPORT_en = io_req_valid & io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17]
  assign rockettile_dcache_data_arrays_0_rdata_data_en = io_req_valid & ~io_req_bits_write;	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:77:{39,42}]
  rockettile_dcache_data_arrays_0 rockettile_dcache_data_arrays_0 (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (io_req_bits_addr[9:2]),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:59:31]
    .RW0_en    (rockettile_dcache_data_arrays_0_rdata_data_en | rockettile_dcache_data_arrays_0_rdata_MPORT_en),	// @[generators/rocket-chip/src/main/scala/rocket/DCache.scala:72:17, :77:39, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (io_req_bits_write),
    .RW0_wdata (io_req_bits_wdata),
    .RW0_rdata (io_resp_0),
    .RW0_wmask (io_req_bits_eccMask)
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
endmodule

