// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Directory(	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
  input        clock,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
  input        reset,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
  output       io_write_ready,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  input        io_write_valid,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  input  [4:0] io_write_bits_set,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  input        io_write_bits_way,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  input        io_write_bits_data_dirty,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  input  [1:0] io_write_bits_data_state,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  input        io_write_bits_data_clients,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  input  [3:0] io_write_bits_data_tag,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  input        io_read_valid,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  input  [4:0] io_read_bits_set,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  input  [3:0] io_read_bits_tag,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  output       io_result_bits_dirty,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  output [1:0] io_result_bits_state,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  output       io_result_bits_clients,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  output [3:0] io_result_bits_tag,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  output       io_result_bits_hit,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  output       io_result_bits_way,	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
  output       io_ready	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
);

  wire        cc_dir_MPORT_mask_1;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:100:65]
  wire        cc_dir_MPORT_mask_0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:100:65]
  wire [7:0]  cc_dir_MPORT_data_1;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:99:44]
  wire [4:0]  cc_dir_MPORT_addr;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:98:10]
  wire        cc_dir_MPORT_en;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:96:14]
  wire        _victimLFSR_prng_io_out_9;	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire        _write_q_io_deq_valid;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [4:0]  _write_q_io_deq_bits_set;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        _write_q_io_deq_bits_way;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        _write_q_io_deq_bits_data_dirty;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [1:0]  _write_q_io_deq_bits_data_state;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        _write_q_io_deq_bits_data_clients;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [3:0]  _write_q_io_deq_bits_data_tag;	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [15:0] _cc_dir_RW0_rdata;	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  reg  [5:0]  wipeCount;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:79:26]
  reg         wipeOff;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:80:24]
  assign cc_dir_MPORT_en = ~io_read_valid & (~(wipeCount[5]) & ~wipeOff | _write_q_io_deq_valid);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:79:26, :80:24, :81:27, :85:{9,22}, :86:23, :90:{24,37}, :96:14, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign cc_dir_MPORT_addr = wipeCount[5] ? _write_q_io_deq_bits_set : wipeCount[4:0];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:79:26, :81:27, :82:26, :98:10, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign cc_dir_MPORT_data_1 = wipeCount[5] ? {_write_q_io_deq_bits_data_dirty, _write_q_io_deq_bits_data_state, _write_q_io_deq_bits_data_clients, _write_q_io_deq_bits_data_tag} : 8'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:79:26, :81:27, :99:{44,71}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign cc_dir_MPORT_mask_0 = ~_write_q_io_deq_bits_way | ~(wipeCount[5]);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:79:26, :81:27, :85:9, :100:{51,65}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign cc_dir_MPORT_mask_1 = _write_q_io_deq_bits_way | ~(wipeCount[5]);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:79:26, :81:27, :85:9, :100:65, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  reg         ren1;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:103:21]
  reg  [3:0]  tag;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:111:36]
  reg  [4:0]  set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:112:36]
  `ifndef SYNTHESIS	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:86:10]
    always @(posedge clock) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:86:10]
      if (~reset & ~(wipeCount[5] | ~io_read_valid)) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:79:26, :81:27, :86:{10,20,23}, :91:10]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:86:10]
          $error("Assertion failed\n    at Directory.scala:86 assert (wipeDone || !io.read.valid)\n");	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:86:10]
        if (`STOP_COND_)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:86:10]
          $fatal;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:86:10]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:91:10]
          $error("Assertion failed\n    at Directory.scala:91 assert (!io.read.valid || wipeDone)\n");	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:91:10]
        if (`STOP_COND_)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:91:10]
          $fatal;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:91:10]
      end
      if (~reset & ~(~ren1 | {1'h0, ~_victimLFSR_prng_io_out_9} + {1'h0, _victimLFSR_prng_io_out_9} == 2'h1)) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :86:10, :103:21, :119:57, :121:11, :123:{10,17,28,42}, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:123:10]
          $error("Assertion failed\n    at Directory.scala:123 assert (!ren2 || PopCount(victimWayOH) === 1.U)\n");	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:123:10]
        if (`STOP_COND_)	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:123:10]
          $fatal;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:123:10]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        setQuash = _write_q_io_deq_valid & _write_q_io_deq_bits_set == set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:112:36, :125:{31,45}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        tagMatch = _write_q_io_deq_bits_data_tag == tag;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:111:36, :126:34, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        _hits_T_6 = _cc_dir_RW0_rdata[3:0] == tag & (|(_cc_dir_RW0_rdata[6:5])) & (~setQuash | _write_q_io_deq_bits_way);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:111:36, :125:31, :129:40, :131:{11,19,30,42,46,56}, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire        _hits_T_13 = _cc_dir_RW0_rdata[11:8] == tag & (|(_cc_dir_RW0_rdata[14:13])) & (~setQuash | ~_write_q_io_deq_bits_way);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:111:36, :125:31, :129:40, :131:{11,19,30,42,46,56,63}, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  wire [1:0]  hits = {_hits_T_13, _hits_T_6};	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:130:17, :131:{19,42}]
  wire        _view__T_15 = setQuash & (tagMatch | _write_q_io_deq_bits_way == _victimLFSR_prng_io_out_9);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:125:31, :126:34, :127:29, :136:{105,118}, src/main/scala/chisel3/util/Decoupled.scala:362:21, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  wire        _io_result_bits_way_T_1 = setQuash & tagMatch;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:125:31, :126:34, :137:42]
  always @(posedge clock) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
    if (reset) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
      wipeCount <= 6'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:79:26]
      wipeOff <= 1'h1;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :80:24]
      ren1 <= 1'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :103:21]
    end
    else begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
      if (wipeCount[5] | wipeOff) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:79:26, :80:24, :81:27, :85:{32,44}]
      end
      else	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:79:26, :85:{32,44}]
        wipeCount <= wipeCount + 6'h1;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:79:26, :85:57]
      wipeOff <= 1'h0;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :80:24]
      ren1 <= io_read_valid;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:103:21]
    end
    if (io_read_valid) begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:58:14]
      tag <= io_read_bits_tag;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:111:36]
      set <= io_read_bits_set;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:112:36]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
    initial begin	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
        wipeCount = _RANDOM[/*Zero width*/ 1'b0][5:0];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :79:26]
        wipeOff = _RANDOM[/*Zero width*/ 1'b0][6];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :79:26, :80:24]
        ren1 = _RANDOM[/*Zero width*/ 1'b0][7];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :79:26, :103:21]
        tag = _RANDOM[/*Zero width*/ 1'b0][11:8];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :79:26, :111:36]
        set = _RANDOM[/*Zero width*/ 1'b0][16:12];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :79:26, :112:36]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  cc_dir cc_dir (	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_addr  (cc_dir_MPORT_en ? cc_dir_MPORT_addr : io_read_bits_set),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:96:14, :98:10, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_en    (io_read_valid | cc_dir_MPORT_en),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:96:14, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_clk   (clock),
    .RW0_wmode (~io_read_valid),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:86:23]
    .RW0_wdata ({2{cc_dir_MPORT_data_1}}),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:99:44, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
    .RW0_rdata (_cc_dir_RW0_rdata),
    .RW0_wmask ({cc_dir_MPORT_mask_1, cc_dir_MPORT_mask_0})	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:100:65, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  );	// @[generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26]
  Queue1_DirectoryWrite write_q (	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
    .clock                    (clock),
    .reset                    (reset),
    .io_enq_ready             (io_write_ready),
    .io_enq_valid             (io_write_valid),
    .io_enq_bits_set          (io_write_bits_set),
    .io_enq_bits_way          (io_write_bits_way),
    .io_enq_bits_data_dirty   (io_write_bits_data_dirty),
    .io_enq_bits_data_state   (io_write_bits_data_state),
    .io_enq_bits_data_clients (io_write_bits_data_clients),
    .io_enq_bits_data_tag     (io_write_bits_data_tag),
    .io_deq_ready             (~io_read_valid),	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:86:23]
    .io_deq_valid             (_write_q_io_deq_valid),
    .io_deq_bits_set          (_write_q_io_deq_bits_set),
    .io_deq_bits_way          (_write_q_io_deq_bits_way),
    .io_deq_bits_data_dirty   (_write_q_io_deq_bits_data_dirty),
    .io_deq_bits_data_state   (_write_q_io_deq_bits_data_state),
    .io_deq_bits_data_clients (_write_q_io_deq_bits_data_clients),
    .io_deq_bits_data_tag     (_write_q_io_deq_bits_data_tag)
  );	// @[src/main/scala/chisel3/util/Decoupled.scala:362:21]
  MaxPeriodFibonacciLFSR victimLFSR_prng (	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
    .clock        (clock),
    .reset        (reset),
    .io_increment (io_read_valid),
    .io_out_0     (/* unused */),
    .io_out_1     (/* unused */),
    .io_out_2     (/* unused */),
    .io_out_3     (/* unused */),
    .io_out_4     (/* unused */),
    .io_out_5     (/* unused */),
    .io_out_6     (/* unused */),
    .io_out_7     (/* unused */),
    .io_out_8     (/* unused */),
    .io_out_9     (_victimLFSR_prng_io_out_9),
    .io_out_10    (/* unused */),
    .io_out_11    (/* unused */),
    .io_out_12    (/* unused */),
    .io_out_13    (/* unused */),
    .io_out_14    (/* unused */),
    .io_out_15    (/* unused */)
  );	// @[src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  assign io_result_bits_dirty = (|hits) ? _hits_T_6 & _cc_dir_RW0_rdata[7] | _hits_T_13 & _cc_dir_RW0_rdata[15] : _view__T_15 ? _write_q_io_deq_bits_data_dirty : ~_victimLFSR_prng_io_out_9 & _cc_dir_RW0_rdata[7] | _victimLFSR_prng_io_out_9 & _cc_dir_RW0_rdata[15];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :119:57, :129:40, :130:17, :131:{19,42}, :133:18, :136:{67,95,105}, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/chisel3/util/Decoupled.scala:362:21, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  assign io_result_bits_state = (|hits) ? (_hits_T_6 ? _cc_dir_RW0_rdata[6:5] : 2'h0) | (_hits_T_13 ? _cc_dir_RW0_rdata[14:13] : 2'h0) : _view__T_15 ? _write_q_io_deq_bits_data_state : (_victimLFSR_prng_io_out_9 ? 2'h0 : _cc_dir_RW0_rdata[6:5]) | (_victimLFSR_prng_io_out_9 ? _cc_dir_RW0_rdata[14:13] : 2'h0);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :129:40, :130:17, :131:{19,42}, :133:18, :136:{67,95,105}, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/chisel3/util/Decoupled.scala:362:21, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  assign io_result_bits_clients = (|hits) ? _hits_T_6 & _cc_dir_RW0_rdata[4] | _hits_T_13 & _cc_dir_RW0_rdata[12] : _view__T_15 ? _write_q_io_deq_bits_data_clients : ~_victimLFSR_prng_io_out_9 & _cc_dir_RW0_rdata[4] | _victimLFSR_prng_io_out_9 & _cc_dir_RW0_rdata[12];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :119:57, :129:40, :130:17, :131:{19,42}, :133:18, :136:{67,95,105}, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/chisel3/util/Decoupled.scala:362:21, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  assign io_result_bits_tag = (|hits) ? (_hits_T_6 ? _cc_dir_RW0_rdata[3:0] : 4'h0) | (_hits_T_13 ? _cc_dir_RW0_rdata[11:8] : 4'h0) : _view__T_15 ? _write_q_io_deq_bits_data_tag : (_victimLFSR_prng_io_out_9 ? 4'h0 : _cc_dir_RW0_rdata[3:0]) | (_victimLFSR_prng_io_out_9 ? _cc_dir_RW0_rdata[11:8] : 4'h0);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :129:40, :130:17, :131:{19,42}, :133:18, :136:{67,95,105}, generators/rocket-chip/src/main/scala/util/DescribedSRAM.scala:17:26, src/main/scala/chisel3/util/Decoupled.scala:362:21, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  assign io_result_bits_hit = (|hits) | _io_result_bits_way_T_1 & (|_write_q_io_deq_bits_data_state);	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :130:17, :133:18, :137:{29,42,54,75}, src/main/scala/chisel3/util/Decoupled.scala:362:21]
  assign io_result_bits_way = (|hits) ? _hits_T_13 : _io_result_bits_way_T_1 ? _write_q_io_deq_bits_way : _victimLFSR_prng_io_out_9;	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :130:17, :131:{19,42}, :133:18, :137:42, :138:{28,53}, src/main/scala/chisel3/util/Decoupled.scala:362:21, src/main/scala/chisel3/util/random/PRNG.scala:91:22]
  assign io_ready = wipeCount[5];	// @[generators/rocket-chip-inclusive-cache/design/craft/inclusivecache/src/Directory.scala:56:7, :79:26, :81:27]
endmodule

