// Generated by CIRCT firtool-1.75.0
module MemoryBus(	// @[generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9]
  input         auto_coupler_to_onchipsram_fragmenter_anon_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_onchipsram_fragmenter_anon_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [1:0]  auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [7:0]  auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [3:0]  auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_coupler_to_onchipsram_fragmenter_anon_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_coupler_to_onchipsram_fragmenter_anon_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_coupler_to_onchipsram_fragmenter_anon_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [1:0]  auto_coupler_to_onchipsram_fragmenter_anon_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [7:0]  auto_coupler_to_onchipsram_fragmenter_anon_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_coupler_to_onchipsram_fragmenter_anon_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_fixedClockNode_anon_out_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_fixedClockNode_anon_out_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_mbus_clock_groups_in_member_mbus_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_mbus_clock_groups_in_member_mbus_0_reset,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_bus_xing_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_bus_xing_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_bus_xing_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_bus_xing_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_bus_xing_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [2:0]  auto_bus_xing_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_bus_xing_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [3:0]  auto_bus_xing_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input  [31:0] auto_bus_xing_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_bus_xing_in_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  input         auto_bus_xing_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output        auto_bus_xing_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_bus_xing_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_bus_xing_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [2:0]  auto_bus_xing_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
  output [31:0] auto_bus_xing_in_d_bits_data	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:107:25]
);

  wire        _coupler_to_onchipsram_auto_tl_in_a_ready;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _coupler_to_onchipsram_auto_tl_in_d_valid;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_onchipsram_auto_tl_in_d_bits_opcode;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_onchipsram_auto_tl_in_d_bits_size;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [2:0]  _coupler_to_onchipsram_auto_tl_in_d_bits_source;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire [31:0] _coupler_to_onchipsram_auto_tl_in_d_bits_data;	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  wire        _picker_auto_out_a_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
  wire [2:0]  _picker_auto_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
  wire [2:0]  _picker_auto_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
  wire [2:0]  _picker_auto_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
  wire [2:0]  _picker_auto_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
  wire [31:0] _picker_auto_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
  wire [3:0]  _picker_auto_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
  wire [31:0] _picker_auto_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
  wire        _picker_auto_out_a_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
  wire        _picker_auto_out_d_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
  wire        _fixedClockNode_auto_anon_out_0_clock;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
  wire        _fixedClockNode_auto_anon_out_0_reset;	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
  FixedClockBroadcast_2 fixedClockNode (	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_anon_in_clock    (auto_mbus_clock_groups_in_member_mbus_0_clock),
    .auto_anon_in_reset    (auto_mbus_clock_groups_in_member_mbus_0_reset),
    .auto_anon_out_1_clock (auto_fixedClockNode_anon_out_clock),
    .auto_anon_out_1_reset (auto_fixedClockNode_anon_out_reset),
    .auto_anon_out_0_clock (_fixedClockNode_auto_anon_out_0_clock),
    .auto_anon_out_0_reset (_fixedClockNode_auto_anon_out_0_reset)
  );	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
  ProbePicker picker (	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
    .clock                   (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                   (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_in_a_ready         (auto_bus_xing_in_a_ready),
    .auto_in_a_valid         (auto_bus_xing_in_a_valid),
    .auto_in_a_bits_opcode   (auto_bus_xing_in_a_bits_opcode),
    .auto_in_a_bits_param    (auto_bus_xing_in_a_bits_param),
    .auto_in_a_bits_size     (auto_bus_xing_in_a_bits_size),
    .auto_in_a_bits_source   (auto_bus_xing_in_a_bits_source),
    .auto_in_a_bits_address  (auto_bus_xing_in_a_bits_address),
    .auto_in_a_bits_mask     (auto_bus_xing_in_a_bits_mask),
    .auto_in_a_bits_data     (auto_bus_xing_in_a_bits_data),
    .auto_in_a_bits_corrupt  (auto_bus_xing_in_a_bits_corrupt),
    .auto_in_d_ready         (auto_bus_xing_in_d_ready),
    .auto_in_d_valid         (auto_bus_xing_in_d_valid),
    .auto_in_d_bits_opcode   (auto_bus_xing_in_d_bits_opcode),
    .auto_in_d_bits_size     (auto_bus_xing_in_d_bits_size),
    .auto_in_d_bits_source   (auto_bus_xing_in_d_bits_source),
    .auto_in_d_bits_data     (auto_bus_xing_in_d_bits_data),
    .auto_out_a_ready        (_coupler_to_onchipsram_auto_tl_in_a_ready),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_out_a_valid        (_picker_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_picker_auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (_picker_auto_out_a_bits_param),
    .auto_out_a_bits_size    (_picker_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_picker_auto_out_a_bits_source),
    .auto_out_a_bits_address (_picker_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_picker_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_picker_auto_out_a_bits_data),
    .auto_out_a_bits_corrupt (_picker_auto_out_a_bits_corrupt),
    .auto_out_d_ready        (_picker_auto_out_d_ready),
    .auto_out_d_valid        (_coupler_to_onchipsram_auto_tl_in_d_valid),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_out_d_bits_opcode  (_coupler_to_onchipsram_auto_tl_in_d_bits_opcode),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_out_d_bits_size    (_coupler_to_onchipsram_auto_tl_in_d_bits_size),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_out_d_bits_source  (_coupler_to_onchipsram_auto_tl_in_d_bits_source),	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .auto_out_d_bits_data    (_coupler_to_onchipsram_auto_tl_in_d_bits_data)	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
  );	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
  TLInterconnectCoupler_mbus_to_onchipsram coupler_to_onchipsram (	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
    .clock                                   (_fixedClockNode_auto_anon_out_0_clock),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .reset                                   (_fixedClockNode_auto_anon_out_0_reset),	// @[generators/rocket-chip/src/main/scala/prci/ClockGroup.scala:115:114]
    .auto_fragmenter_anon_out_a_ready        (auto_coupler_to_onchipsram_fragmenter_anon_out_a_ready),
    .auto_fragmenter_anon_out_a_valid        (auto_coupler_to_onchipsram_fragmenter_anon_out_a_valid),
    .auto_fragmenter_anon_out_a_bits_opcode  (auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_opcode),
    .auto_fragmenter_anon_out_a_bits_param   (auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_param),
    .auto_fragmenter_anon_out_a_bits_size    (auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_size),
    .auto_fragmenter_anon_out_a_bits_source  (auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_source),
    .auto_fragmenter_anon_out_a_bits_address (auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_address),
    .auto_fragmenter_anon_out_a_bits_mask    (auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_mask),
    .auto_fragmenter_anon_out_a_bits_data    (auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_data),
    .auto_fragmenter_anon_out_a_bits_corrupt (auto_coupler_to_onchipsram_fragmenter_anon_out_a_bits_corrupt),
    .auto_fragmenter_anon_out_d_ready        (auto_coupler_to_onchipsram_fragmenter_anon_out_d_ready),
    .auto_fragmenter_anon_out_d_valid        (auto_coupler_to_onchipsram_fragmenter_anon_out_d_valid),
    .auto_fragmenter_anon_out_d_bits_opcode  (auto_coupler_to_onchipsram_fragmenter_anon_out_d_bits_opcode),
    .auto_fragmenter_anon_out_d_bits_size    (auto_coupler_to_onchipsram_fragmenter_anon_out_d_bits_size),
    .auto_fragmenter_anon_out_d_bits_source  (auto_coupler_to_onchipsram_fragmenter_anon_out_d_bits_source),
    .auto_fragmenter_anon_out_d_bits_data    (auto_coupler_to_onchipsram_fragmenter_anon_out_d_bits_data),
    .auto_tl_in_a_ready                      (_coupler_to_onchipsram_auto_tl_in_a_ready),
    .auto_tl_in_a_valid                      (_picker_auto_out_a_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
    .auto_tl_in_a_bits_opcode                (_picker_auto_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
    .auto_tl_in_a_bits_param                 (_picker_auto_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
    .auto_tl_in_a_bits_size                  (_picker_auto_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
    .auto_tl_in_a_bits_source                (_picker_auto_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
    .auto_tl_in_a_bits_address               (_picker_auto_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
    .auto_tl_in_a_bits_mask                  (_picker_auto_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
    .auto_tl_in_a_bits_data                  (_picker_auto_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
    .auto_tl_in_a_bits_corrupt               (_picker_auto_out_a_bits_corrupt),	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
    .auto_tl_in_d_ready                      (_picker_auto_out_d_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/ProbePicker.scala:69:28]
    .auto_tl_in_d_valid                      (_coupler_to_onchipsram_auto_tl_in_d_valid),
    .auto_tl_in_d_bits_opcode                (_coupler_to_onchipsram_auto_tl_in_d_bits_opcode),
    .auto_tl_in_d_bits_size                  (_coupler_to_onchipsram_auto_tl_in_d_bits_size),
    .auto_tl_in_d_bits_source                (_coupler_to_onchipsram_auto_tl_in_d_bits_source),
    .auto_tl_in_d_bits_data                  (_coupler_to_onchipsram_auto_tl_in_d_bits_data)
  );	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyScope.scala:98:27]
endmodule

